baseURL = "https://stanleykerr.co.uk"
languageCode = "en-us"
paginate = "16"
summaryLength = "40"
theme = "parsa-hugo"
title = "Stanley Kerr - Portrait Artist"
[[menu.main]]
name = "Abstracts"
parent = "Paintings"
url = "abstracts/"
weight = 3
[[menu.main]]
name = "Landscapes"
parent = "Paintings"
url = "landscapes/"
weight = 2
[[menu.main]]
name = "Portraits"
parent = "Paintings"
url = "portraits/"
weight = 1
[[menu.main]]
URL = "categories/collections/"
name = "Paintings"
url = "paintings/"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 3
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
address = ""
author = "Stanley Kerr"
author_image = "uploads/banner-img.png"
og_image = "/uploads/rich-link-image-2.jpg"
sitename = "Stanley Kerr - Portrait Artist"
bio = "Portrait Artist | Oils on Canvas"
contact_form_action = "#"
copyright = "&copy; Stanley Kerr 2020. All rights reserved"
description = "Award winning portrait artist. Extraordinary in their psychological acuity, Stanley Kerr's portraits evince a skilful grasp of colour and texture. They disclose a fleeting truth that is as much technical intuition as emotional radar. Faces are taken from the side, obscured, in awkward postures, at times in traditional 3/4 profile, limned in subtle tonalities and with stark expressive power that calls on affinities as diverse as Renaissance portraiture and David Hockney, with whom Stanley Kerr studied."
email = "stanleykerr@yahoo.com"
google_analitycs_id = "G-72EFKXGGRE"
home = "Home"
layout = "1"
logo = "uploads/logo-1.png"
mainSections = ["portraits", "abstracts", "landscapes"]
mobile = ""
preloader = false
search = false
[params.instafeed]
access_token = "4044026246.1677ed0.8896752506ed4402a0519d23b8f50a17"
enable = false
user_id = "4044026246"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.social]]
URL = "https://instagram.com/stanleyskerr"
icon = "ti-instagram"
